// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register";
  };
  "./index.tsx": {
    id: "index";
    page: "/";
  };
  "./login.tsx": {
    id: "login";
    page: "/login";
  };
  "./register.tsx": {
    id: "register";
    page: "/register";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "index": typeof import("./app/./index.tsx");
  "login": typeof import("./app/./login.tsx");
  "register": typeof import("./app/./register.tsx");
};